import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const text = path => readFile(new URL(`../${path}`, import.meta.url), 'utf8')

test('client is one removable DSH settings section, not a second application shell', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /slots\.inject\(['"]settings\.section['"]/)
  assert.match(source, /id:\s*['"]codex-subscription['"]/)
  assert.match(source, /['"]\/codex-subscription['"]/) // RPC channel
  assert.doesNotMatch(source, /wsl043/iu)
  assert.match(source, /login\/start/)
  assert.match(source, /login\/status/)
  assert.match(source, /local-auth\/import/)
  assert.match(source, /localLogin/)
  assert.match(source, /['"]usage['"]/)
  assert.doesNotMatch(source, /['"]cache['"]|CacheDiagnostics|CodexCacheTelemetry/)
  assert.doesNotMatch(source, /createRoot|ReactDOM|index\.html|localStorage|sessionStorage|accessToken|refreshToken/)
})

test('settings exposes one secret-free support diagnostic that can be copied deliberately', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /['"]diagnostics['"]/u)
  assert.match(source, /navigator\.clipboard\.writeText/u)
  assert.match(source, /JSON\.stringify\(report, null, 2\)/u)
  assert.match(source, /diagnosticsCopy/u)
  assert.doesNotMatch(source, /accessToken|refreshToken|accountId/u)
})

test('the English settings navigation label fits the DSH sidebar', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /const en = \{[\s\S]*?nav:\s*['"]Codex['"][\s\S]*?title:\s*['"]Codex subscription['"]/u)
})

test('beta quota badge uses the public composer slot before the model selector', async () => {
  const [client, host, contract] = await Promise.all([
    text('src/client.jsx'), text('src/index.js'), text('src/settings-contract.js'),
  ])
  assert.match(client, /slots\.inject\(['"]conversation\.input\.right['"]/u)
  assert.match(client, /name:\s*['"]conversation\.input\.right['"]/u)
  assert.match(client, /id:\s*['"]codex-subscription-quota['"]/u)
  assert.match(client, /modelDirectories/u)
  assert.doesNotMatch(client, /sidebar\.footer\.action/u)
  assert.match(client, /settingsScope\.bind\(\{\s*namespace:\s*SETTINGS_NAMESPACE\s*\}\)/u)
  assert.match(client, /scope\.set\(field,\s*value\)/u)
  assert.match(client, /preferences\/status/u)
  assert.match(client, /preferences\/update/u)
  assert.match(client, /native\.status === ['"]ready['"]/u)
  assert.match(client, /QUICK_QUOTA_FIELD/u)
  assert.match(client, /role=['"]switch['"]/u)
  assert.match(client, /aria-checked=/u)
  assert.match(client, /role=['"]status['"]/u)
  assert.match(client, /preferenceSnapshot\.status === ['"]ready['"] && preferenceSnapshot\.visible/u)
  assert.doesNotMatch(client, /onPointerDown|onMouseDown|onContextMenu/u)
  assert.doesNotMatch(client, /localStorage|sessionStorage/u)
  assert.match(host, /export const inject = \[[^\]]*['"]settings['"]/u)
  assert.match(host, /ctx\.settings\.register/u)
  assert.match(host, /settings\.watch/u)
  assert.match(host, /preferences\/status/u)
  assert.match(host, /preferences\/update/u)
  assert.match(host, /QUICK_QUOTA_FIELD/u)
  assert.match(contract, /quickQuotaVisible/u)
  assert.match(contract, /DEFAULT_QUICK_QUOTA_VISIBLE\s*=\s*false/u)
  assert.match(contract, /DEFAULT_SEARCH_PROVIDER\s*=\s*SEARCH_PROVIDER_DSH/u)
})

test('composer quota is neutral and the detailed quota grid is compact', async () => {
  const source = await text('src/client.jsx')
  const composerRule = source.match(/\.codexComposerQuota\{[^}]+\}/u)?.[0]
  assert.ok(composerRule, 'missing composer quota base rule')
  assert.match(composerRule, /var\(--dsw-alias-label-/u)
  assert.match(composerRule, /display:\s*inline-flex/u)
  assert.match(composerRule, /align-items:\s*center/u)
  assert.match(composerRule, /height:\s*28px/u)
  assert.doesNotMatch(composerRule, /margin(?:-right)?:\s*-\d/u, 'composer alignment must not depend on negative margins')
  assert.match(composerRule, /font-size:\s*12px/u)
  assert.match(composerRule, /line-height:\s*20px/u)
  assert.doesNotMatch(composerRule, /brand|success|error|#[0-9a-f]{3,8}|rgb\(/iu)
  assert.match(source, /\.codexSubscriptionUsageCard\{[^}]*padding:\s*12px 14px[^}]*gap:\s*9px/u)
  assert.match(source, /\.codexSubscriptionLimit\{[^}]*padding:\s*9px 12px[^}]*gap:\s*6px/u)
  assert.match(source, /\.codexSubscriptionLimit progress\{[^}]*height:\s*4px/u)
  assert.doesNotMatch(source, /fill\(t\(['"]used['"]\),\s*\{\s*value:\s*percent\(window\.usedPercent\)/u)
})

test('settings offer explicit DSH or Codex search and mark quick quota as beta', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /searchProvider/u)
  assert.match(source, /searchDsh/u)
  assert.match(source, /searchCodex/u)
  assert.match(source, /role=['"]radiogroup['"]/u)
  assert.match(source, /type=['"]radio['"]/u)
  assert.match(source, /className=['"]codexSubscriptionSearchInput['"]/u)
  assert.match(source, /\.codexSubscriptionSearchInput\{[^}]*width:\s*14px[^}]*height:\s*14px/u)
  assert.doesNotMatch(source, /\.codexSubscriptionSearchChoice input\{[^}]*opacity:\s*0/u)
  assert.doesNotMatch(source, /role=['"]radio['"]/u)
  assert.match(source, /preferenceFailed/u)
  assert.match(source, /snapshot\.error/u)
  assert.match(source, /quickQuotaBeta/u)
})

test('beta speed control is persisted inside the model menu and hidden from the composer while standard', async () => {
  const [client, host, contract] = await Promise.all([
    text('src/client.jsx'), text('src/index.js'), text('src/settings-contract.js'),
  ])
  assert.match(contract, /SPEED_MODE_FIELD\s*=\s*['"]speedMode['"]/u)
  assert.match(contract, /DEFAULT_SPEED_MODE\s*=\s*SPEED_MODE_STANDARD/u)
  assert.match(host, /SPEED_MODE_FIELD/u)
  assert.match(host, /resolveSpeedMode/u)
  assert.match(client, /speedTitle/u)
  assert.match(client, /speedStandard/u)
  assert.match(client, /speedFast/u)
  assert.match(client, /speedFastHint/u)
  assert.match(client, /BoltIcon/u)
  assert.doesNotMatch(client, />\s*(?:⚡|1×)\s*</u, 'speed control must not use a font glyph')
  assert.match(client, /function CodexModelSelect/u)
  assert.match(client, /slots\.inject\(['"]conversation\.input\.model['"]/u)
  assert.match(client, /name:\s*['"]conversation\.input\.model['"][\s\S]*?priority:\s*-10/u)
  assert.match(client, /pane === ['"]speed['"]/u)
  assert.match(client, /speedSupported &&[\s\S]*?t\(['"]speedTitle['"]\)/u)
  assert.match(client, /fast && <BoltIcon className=['"]codexModelSelectBolt['"]/u)
  assert.match(client, /\.codexModelSelectMenu\{overflow:visible\}/u, 'the nested speed menu must not be clipped by the root menu')
  assert.match(client, /\.codexModelSelectSubmenu\{right:calc\(100% \+ 8px\)/u, 'the submenu should open beside the root menu like Codex')
  assert.doesNotMatch(client, /codexComposerSpeed|codexComposerControls/u)
  assert.match(client, /supportsCodexFastMode/u)
  assert.match(client, /slots\.inject\(['"]conversation\.input\.right['"]/u)
  assert.doesNotMatch(client, /codexSubscriptionSpeedChoices/u, 'speed belongs in the composer, not Settings')
  assert.doesNotMatch(client, /localStorage|sessionStorage/u)
})

test('quota is the primary surface with reset, freshness, loading, and empty-state semantics', async () => {
  const source = await text('src/client.jsx')
  for (const token of ['resetsAt', 'fetchedAt', 'usageLoading', 'usageEmpty', 'usageUpdated', 'resetCredits']) {
    assert.match(source, new RegExp(token))
  }
  assert.match(source, /<time\b[^>]*dateTime=/u)
  assert.match(source, /<progress\b[^>]*value=\{window\.remainingPercent\}/u)
  assert.match(source, /::-webkit-progress-value/u)
  assert.match(source, /var\(--dsw-alias-brand-primary,\s*#3964fe\)/u)
  assert.match(source, /aria-live=['"]polite['"]/u)
  assert.match(source, /useRef\(0\)/u)
  assert.match(source, /const visibleUsage = signedIn \? usage : undefined/u)
  assert.match(source, /windowWeekly/u)
  assert.match(source, /windowFiveHours/u)
  assert.match(source, /isApproximateWindow/u)
  assert.doesNotMatch(source, /codex_bengalfox|GPT-5\.3-Codex-Spark/u, 'model quota labels must come from the backend')
  assert.match(source, /refreshing/u)
  assert.match(source, /className=['"]codexSubscriptionRefresh['"]/u)
  assert.match(source, /\.codexSubscriptionRefresh\{[^}]*white-space:\s*nowrap/u)
  assert.match(source, /monthlyCreditLimit/u)
  assert.match(source, /creditsBalance/u)
  assert.match(source, /creditsNote/u)
  assert.match(source, /额外 Credits 余额/u)
  assert.match(source, /Credits 月度消费上限/u)
  assert.match(source, /visibleUsage\?\.credits === undefined && visibleUsage\?\.individualLimit === undefined/u)
  assert.match(source, /individualLimit\.used/u)
  assert.doesNotMatch(source, /individualLimit\.remaining(?!Percent)/u)
})

test('settings keep support diagnostics actionable and omit internal cache or route policy copy', async () => {
  const source = await text('src/client.jsx')
  assert.doesNotMatch(source, /CacheDiagnostics|Technical diagnostics|技术诊断|codexSubscriptionSafety/u)
  assert.match(source, /diagnosticsHint/u)
  assert.doesNotMatch(source, /routePolicy|noFallback|searchIntro|quickQuotaHint|usageIntro|codexSubscriptionIntro|codexSubscriptionRoutePolicy/u)
})

test('account and preference failures stop loading and offer an in-place retry', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /accountError === undefined\s*\?\s*<AccountCard/u)
  assert.match(source, /<AccountFailureCard/u)
  assert.match(source, /accountRetry/u)
  assert.match(source, /preference\.retry\(\)/u)
  assert.match(source, /preferenceRetry/u)
  assert.match(source, /role=['"]alert['"][\s\S]*?Button/u)
  assert.match(source, /account === undefined \? null : <UsageCard/u)
  assert.doesNotMatch(source, /accountState === ['"](?:loading|error)['"]/u)
})

test('build emits host entries and a DSH module-loader client', async () => {
  const config = await text('tsdown.config.mjs')
  assert.match(config, /src\/index\.js/)
  assert.doesNotMatch(config, /src\/boundary\.js/)
  assert.match(config, /src\/client\.jsx/)
  assert.match(config, /window\.__ModuleLoader__\.load/)
  assert.match(config, /['"]dsh-codex-subscription['"]/)
  assert.doesNotMatch(config, /wsl043/iu)
})

test('generated Codex images use a plugin-owned viewer across supported DSH releases', async () => {
  const [source, manifest, config] = await Promise.all([
    text('src/client.jsx'), text('package.json'), text('tsdown.config.mjs'),
  ])
  assert.doesNotMatch(source, /from ['"]@deepseek-ai\/dsh-client-ui-attachment['"]/u)
  assert.match(source, /function CodexGeneratedImage/u)
  assert.match(source, /role="dialog"/u)
  assert.match(source, /event\.key === 'Escape'/u)
  assert.match(source, /event\.key === 'Tab'/u)
  assert.match(source, /closeRef\.current\?\.focus/u)
  assert.match(source, /tool\.call\.toolview/u)
  assert.match(source, /key:\s*['"]codex_image_generate['"]/u)
  assert.match(source, /resolveImage\(sessionId,\s*attachment\)/u)
  assert.match(source, /block\.content/u)
  assert.match(manifest, /@deepseek-ai\/dsh-client-ui-tool/u)
  assert.doesNotMatch(config, /@deepseek-ai\/dsh-client-ui-attachment/u)
})
