import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = path => readFile(new URL(`../${path}`, import.meta.url), 'utf8')
// These contracts cover the client entry and its authored copy, styles and download helper.
const text = path => path === 'src/client.jsx'
  ? Promise.all([path, 'src/rpc-contract.js', 'src/client-shared.js', 'src/client-account.jsx', 'src/client-composer-quota.jsx', 'src/client-diagnostics.jsx', 'src/client-model-select.jsx', 'src/client-preferences.jsx', 'src/client-quota.jsx', 'src/client-section.jsx', 'src/client-usage.jsx', 'src/client-locales.js', 'src/client-styles.js', 'src/client-images.jsx', 'src/original-image-download.js'].map(read)).then(parts => parts.join('\n'))
  : path === 'src/index.js' ? Promise.all([path, 'src/subscription-rpc.js'].map(read)).then(parts => parts.join('\n')) : read(path)

test('generated image loader uses the installed DSH UI conversation image API', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /['"]uiConversation['"]/u)
  const method = /loadImage: attachment => uiConversation\.(\w+)\(sessionId, attachment\)/u.exec(source)?.[1]
  assert.equal(method, 'imageUrl')
  const packageUrl = import.meta.resolve('@deepseek-ai/dsh-client-ui-conversation/package.json')
  const [assembly, client] = await Promise.all([
    readFile(new URL('./lib/types/client/conversation/assembly.d.ts', packageUrl), 'utf8'),
    readFile(new URL('./lib/types/client/index.d.ts', packageUrl), 'utf8'),
  ])
  assert.ok(assembly.includes(`${method}(sessionId: SessionId, attachment: ImageAttachmentRef): Promise<string>`))
  assert.match(client, /uiConversation:\s*import\('\.\/conversation\/assembly\.ts'\)\.UiConversation/u)
  assert.match(source, /Promise\.resolve\(\)\.then\(\(\) => loadImage\(attachment\)\)/u)
})

test('client is one removable DSH settings section, not a second application shell', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /slots\.inject\(['"]settings\.section['"]/)
  assert.match(source, /id:\s*['"]codex-subscription['"]/)
  assert.match(source, /['"]\/codex-subscription['"]/) // RPC channel
  const withoutRepositorySupportLink = source.replace('https://github.com/WSL043/dsh-codex-subscription/issues/new?template=install-problem.yml', '')
  assert.doesNotMatch(withoutRepositorySupportLink, /wsl043/iu)
  assert.match(source, /login\/start/)
  assert.match(source, /login\/status/)
  assert.match(source, /local-auth\/import/)
  assert.match(source, /localLogin/)
  assert.match(source, /['"]usage['"]/)
  assert.doesNotMatch(source, /['"]cache['"]|CacheDiagnostics|CodexCacheTelemetry/)
  assert.doesNotMatch(source, /createRoot|ReactDOM|index\.html|localStorage|sessionStorage|accessToken|refreshToken/)
})

test('settings exposes one secret-free support diagnostic that can be copied deliberately', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /['"]diagnostics['"]/u)
  assert.match(source, /navigator\.clipboard\.writeText/u)
  assert.match(source, /JSON\.stringify\(report, null, 2\)/u)
  assert.match(source, /diagnosticsCopy/u)
  assert.doesNotMatch(source, /accessToken|refreshToken|accountId/u)
})

test('the English settings navigation label fits the DSH sidebar', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /const en = \{[\s\S]*?nav:\s*['"]Codex['"][\s\S]*?title:\s*['"]Codex subscription['"]/u)
})

test('composer quota modes use the public composer slot before the model selector', async () => {
  const [client, host, contract, controller] = await Promise.all([
    text('src/client.jsx'), text('src/index.js'), text('src/settings-contract.js'), text('src/preference-controller.js'),
  ])
  assert.match(client, /slots\.inject\(['"]conversation\.input\.right['"]/u)
  assert.match(client, /name:\s*['"]conversation\.input\.right['"]/u)
  assert.match(client, /id:\s*['"]codex-subscription-quota['"]/u)
  assert.match(client, /modelDirectories/u)
  assert.match(client, /ctx\.get\(['"]remote\.session['"]\) === undefined/u)
  assert.match(client, /ctx\.inject\(\[['"]remote\.session['"]\], installDirectorySlots\)/u)
  assert.match(client, /scope\.get\(['"]modelDirectories['"]\)/u)
  assert.doesNotMatch(client, /sidebar\.footer\.action/u)
  assert.match(client, /settingsScope\.bind\(\{\s*namespace:\s*SETTINGS_NAMESPACE\s*\}\)/u)
  assert.match(controller, /scope\.set\(field,\s*value\)/u)
  assert.match(controller, /preferences\/status/u)
  assert.match(controller, /preferences\/update/u)
  assert.match(controller, /native\.status === ['"]ready['"]/u)
  assert.match(client, /QUICK_QUOTA_MODE_FIELD/u)
  assert.match(client, /QUICK_QUOTA_MODE_OFF/u)
  assert.match(client, /QUICK_QUOTA_MODE_PERCENT/u)
  assert.match(client, /quotaShowIndicator/u)
  assert.match(client, /QUICK_QUOTA_MODE_BAR/u)
  assert.match(client, /QUICK_QUOTA_MODE_FORECAST/u)
  assert.match(client, /role=['"]radiogroup['"]/u)
  assert.match(client, /type=['"]radio['"]/u)
  assert.match(client, /role=['"]status['"]/u)
  assert.match(client, /preferenceSnapshot\.status === ['"]ready['"] && preferenceSnapshot\.quickQuotaMode !== QUICK_QUOTA_MODE_OFF/u)
  assert.doesNotMatch(client, /onPointerDown|onMouseDown|onContextMenu/u)
  assert.doesNotMatch(client, /localStorage|sessionStorage/u)
  assert.match(host, /export const inject = \[[^\]]*['"]settings['"]/u)
  assert.match(host, /ctx\.settings\.register/u)
  assert.match(host, /settings\.watch/u)
  assert.match(host, /preferences\/status/u)
  assert.match(host, /preferences\/update/u)
  assert.match(host, /QUICK_QUOTA_MODE_FIELD/u)
  assert.match(contract, /QUICK_QUOTA_MODE_FIELD\s*=\s*['"]quickQuotaMode['"]/u)
  assert.match(contract, /LEGACY_QUICK_QUOTA_FIELD\s*=\s*['"]quickQuotaVisible['"]/u)
  assert.match(contract, /DEFAULT_QUICK_QUOTA_MODE\s*=\s*QUICK_QUOTA_MODE_OFF/u)
  assert.match(contract, /DEFAULT_SEARCH_PROVIDER\s*=\s*SEARCH_PROVIDER_AUTO/u)
})

test('runway mode names calibration, idle, and reset-safe states instead of falling back to a bare percentage', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /quickQuotaForecastHint/u)
  assert.match(source, /quickQuotaForecastCalibrating/u)
  assert.match(source, /quickQuotaForecastIdle/u)
  assert.match(source, /quickQuotaForecastUntilReset/u)
  assert.match(source, /quotaForecastCalibrating/u)
  assert.match(source, /quotaForecastIdle/u)
  assert.match(source, /quotaForecastUntilReset/u)
  assert.match(source, /forecast\?\.status === ['"]calibrating['"]/u)
  assert.match(source, /forecast\?\.status === ['"]idle['"]/u)
  assert.match(source, /forecast\.survivesReset/u)
  assert.match(source, /正在校准/u)
  assert.match(source, /足够用到重置/u)
  assert.match(source, /Calibrating/u)
  assert.match(source, /Enough until reset/u)
})

test('composer quota is neutral and the detailed quota grid is compact', async () => {
  const source = await text('src/client.jsx')
  const composerRule = source.match(/\.codexComposerQuota\{[^}]+\}/u)?.[0]
  assert.ok(composerRule, 'missing composer quota base rule')
  assert.match(composerRule, /var\(--dsw-alias-label-/u)
  assert.match(composerRule, /display:\s*inline-flex/u)
  assert.match(composerRule, /align-items:\s*center/u)
  assert.match(composerRule, /height:\s*28px/u)
  assert.doesNotMatch(composerRule, /margin(?:-right)?:\s*-\d/u, 'composer alignment must not depend on negative margins')
  assert.match(composerRule, /font-size:\s*12px/u)
  assert.match(composerRule, /line-height:\s*20px/u)
  assert.doesNotMatch(composerRule, /brand|success|error|#[0-9a-f]{3,8}|rgb\(/iu)
  assert.match(source, /className=['"]codexComposerQuotaBar['"]/u)
  assert.match(source, /<progress[^>]*max=\{100\}[^>]*value=\{quota\.remainingPercent\}/u)
  assert.match(source, /\.codexComposerQuotaBar\{[^}]*width:\s*40px[^}]*height:\s*4px/u)
  assert.doesNotMatch(source.match(/\.codexComposerQuotaBar\{[^}]+\}/u)?.[0] ?? '', /brand|success|error|#[0-9a-f]{3,8}|rgb\(/iu)
  assert.match(source, /\.codexSubscriptionUsageCard\{[^}]*padding:\s*12px 14px[^}]*gap:\s*9px/u)
  assert.match(source, /\.codexSubscriptionLimit\{[^}]*padding:\s*9px 12px[^}]*gap:\s*6px/u)
  assert.match(source, /\.codexSubscriptionLimit progress\{[^}]*height:\s*4px/u)
  assert.doesNotMatch(source, /fill\(t\(['"]used['"]\),\s*\{\s*value:\s*percent\(window\.usedPercent\)/u)
})

test('settings offer automatic and explicit search plus formal composer quota display modes', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /searchProvider/u)
  assert.match(source, /searchDsh/u)
  assert.match(source, /searchCodex/u)
  assert.match(source, /searchAuto/u)
  assert.match(source, /searchScope/u)
  assert.match(source, /自动按当前会话模型分流/u)
  assert.match(source, /Auto follows the current session model/u)
  assert.match(source, /role=['"]radiogroup['"]/u)
  assert.match(source, /type=['"]radio['"]/u)
  assert.match(source, /name=['"]codex-subscription-search-provider['"]/u)
  assert.match(source, /codexSubscriptionSearchChoices codexSubscriptionQuotaModes/u)
  assert.doesNotMatch(source, /role=['"]radio['"]/u)
  assert.match(source, /preferenceFailed/u)
  assert.match(source, /snapshot\.error/u)
  assert.match(source, /quickQuotaOff/u)
  assert.match(source, /quickQuotaPercent/u)
  assert.match(source, /quickQuotaBar/u)
  assert.match(source, /quickQuotaBeta/u)
})

test('settings offer ready-to-use context presets and keep custom limits out of the composer', async () => {
  const source = await text('src/client.jsx')
  const contract = await readFile(new URL('../src/settings-contract.js', import.meta.url), 'utf8')

  assert.match(contract, /CONTEXT_MODE_STANDARD\s*=\s*['"]standard['"]/u)
  assert.match(contract, /CONTEXT_MODE_EXTENDED\s*=\s*['"]extended['"]/u)
  assert.match(contract, /CONTEXT_MODE_CUSTOM\s*=\s*['"]custom['"]/u)
  assert.match(source, /function ContextWindowPreference/u)
  assert.match(source, /<Menu[\s\S]*?selectedId=\{snapshot\.contextMode\}/u)
  assert.match(source, /contextModeItems/u)
  assert.doesNotMatch(source, /<select[^>]*codexSubscriptionContext/u)
  assert.match(source, /contextStandardHint/u)
  assert.match(source, /contextExtendedHint/u)
  assert.match(source, /customContextWindow/u)
  assert.match(source, /type=['"]number['"]/u)
  assert.match(source, /inputMode=['"]numeric['"]/u)
  assert.match(source, /min=\{Math\.min\(MIN_CUSTOM_CONTEXT_WINDOW, model\.maximum\)\}/u)
  assert.match(source, /max=\{model\.maximum\}/u)
  assert.match(source, /clampModelContext\(parsed, modelRows\.find/u)
  assert.match(source, /snapshot\.contextModels/u)
  assert.match(source, /formatContextWindow/u)
  assert.match(source, /parseContextWindow/u)
  assert.match(source, /const nextValue = event\.currentTarget\.value/u)
  assert.doesNotMatch(source, /setDrafts\([^\n]*event\.currentTarget\.value/u, 'React must not retain a pooled input event inside a deferred state updater')

  const composer = await read('src/client-composer-quota.jsx')
  assert.doesNotMatch(composer, /customContextWindow|contextMode/u)
})

test('stable speed control is persisted inside the model menu and hidden from the composer while standard', async () => {
  const [client, host, contract] = await Promise.all([
    text('src/client.jsx'), text('src/index.js'), text('src/settings-contract.js'),
  ])
  assert.match(contract, /SPEED_MODE_FIELD\s*=\s*['"]speedMode['"]/u)
  assert.match(contract, /DEFAULT_SPEED_MODE\s*=\s*SPEED_MODE_STANDARD/u)
  assert.match(host, /SPEED_MODE_FIELD/u)
  assert.match(host, /resolveSpeedMode/u)
  assert.match(client, /speedTitle/u)
  assert.match(client, /speedStandard/u)
  assert.match(client, /speedFast/u)
  assert.match(client, /speedFastHint/u)
  assert.match(client, /BoltIcon/u)
  assert.doesNotMatch(client, />\s*(?:⚡|1×)\s*</u, 'speed control must not use a font glyph')
  assert.match(client, /function CodexModelSelect/u)
  assert.match(client, /slots\.inject\(['"]conversation\.input\.model['"]/u)
  assert.match(client, /name:\s*['"]conversation\.input\.model['"][\s\S]*?priority:\s*-10/u)
  assert.match(client, /pane === ['"]speed['"]/u)
  assert.match(client, /speedSupported &&[\s\S]*?t\(['"]speedTitle['"]\)/u)
  assert.match(client, /fast && <BoltIcon className=['"]codexModelSelectBolt['"]/u)
  assert.match(client, /\.codexModelSelectMenu\{overflow:visible\}/u, 'the nested speed menu must not be clipped by the root menu')
  assert.match(client, /\.codexModelSelectSubmenu\{right:calc\(100% \+ 8px\)/u, 'the submenu should open beside the root menu like Codex')
  assert.doesNotMatch(client, /codexComposerSpeed|codexComposerControls/u)
  assert.match(client, /supportsCodexFastMode/u)
  assert.match(client, /slots\.inject\(['"]conversation\.input\.right['"]/u)
  assert.doesNotMatch(client, /codexSubscriptionSpeedChoices/u, 'speed belongs in the composer, not Settings')
  assert.doesNotMatch(client, /localStorage|sessionStorage/u)
})

test('quota is the primary surface with reset, freshness, loading, and empty-state semantics', async () => {
  const source = await text('src/client.jsx')
  for (const token of ['resetsAt', 'fetchedAt', 'usageLoading', 'usageEmpty', 'usageUpdated', 'resetCredits']) {
    assert.match(source, new RegExp(token))
  }
  assert.match(source, /<time\b[^>]*dateTime=/u)
  assert.match(source, /<progress\b[^>]*value=\{window\.remainingPercent\}/u)
  assert.match(source, /::-webkit-progress-value/u)
  assert.match(source, /var\(--dsw-alias-brand-primary,\s*#3964fe\)/u)
  assert.match(source, /aria-live=['"]polite['"]/u)
  assert.match(source, /useRef\(0\)/u)
  assert.match(source, /const visibleUsage = signedIn \? usage : undefined/u)
  assert.match(source, /windowWeekly/u)
  assert.match(source, /windowFiveHours/u)
  assert.match(source, /isApproximateWindow/u)
  assert.doesNotMatch(source, /codex_bengalfox|GPT-5\.3-Codex-Spark/u, 'model quota labels must come from the backend')
  assert.match(source, /refreshing/u)
  assert.match(source, /className=['"]codexSubscriptionRefresh['"]/u)
  assert.match(source, /\.codexSubscriptionRefresh\{[^}]*white-space:\s*nowrap/u)
  assert.match(source, /monthlyCreditLimit/u)
  assert.match(source, /creditsBalance/u)
  assert.match(source, /creditsNote/u)
  assert.match(source, /额外 Credits 余额/u)
  assert.match(source, /Credits 月度消费上限/u)
  assert.match(source, /visibleUsage\?\.credits === undefined && visibleUsage\?\.individualLimit === undefined/u)
  assert.match(source, /individualLimit\.used/u)
  assert.doesNotMatch(source, /individualLimit\.remaining(?!Percent)/u)
})

test('quota reset redemption requires deliberate multi-step confirmation and never consumes on cancel', async () => {
  const [client, host] = await Promise.all([text('src/client.jsx'), text('src/index.js')])
  assert.match(client, /reset-credit\/prepare/u)
  assert.match(client, /reset-credit\/inspect/u)
  assert.match(client, /reset-credit\/consume/u)
  assert.match(client, /type=['"]checkbox['"]/u)
  assert.match(client, /creditExpiresAt/u)
  assert.match(client, /nextExpiresAt/u)
  assert.match(client, /resetCreditExpires/u)
  assert.match(client, /readyAt/u)
  assert.match(client, /setInterval/u)
  assert.match(client, /resetAcknowledged/u)
  assert.match(client, /resetCountdown/u)
  assert.match(client, /resetAcknowledged && resetCountdown === 0/u)
  assert.doesNotMatch(client, /resetPhrase|confirmPhrase|resetTypeHint/u)
  assert.doesNotMatch(client, /disabled=\{!exhausted/u)
  assert.match(client, /if \(resetBusy\) return/u, 'the final action must be single-flight in the browser')
  assert.match(client, /onClick=\{cancelReset\}/u)
  assert.match(client, /className=['"]codexSubscriptionResetUse['"]/u)
  assert.match(client, /\.codexSubscriptionResetUse:hover:not\(:disabled\)/u)
  assert.match(client, /\.codexSubscriptionResetUse:focus-visible/u)
  assert.match(client, /resetCreditErrorText/u)
  assert.match(client, /key \?\? 'resetFailed'/u, 'unknown host errors must stay bounded and localized')
  assert.doesNotMatch(client, /window\.confirm|window\.prompt/u)
  assert.match(host, /resetCreditService\.consume/u)
  assert.match(host, /resetCreditService\.clear/u)
})

test('a fresh sign-in attempt clears stale client flow state before starting', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /const begin = \(method, label\) => \{\s*flowGeneration\.current \+= 1\s*setFlow\(undefined\);\s*setBusy\(true\); setError\(undefined\)/u)
})

test('settings exposes manual multi-account switching with an explicit remove confirmation', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /addAccount: '添加账号'/u)
  assert.match(source, /call\('account\/select', \{ id \}\)/u)
  assert.match(source, /call\('account\/remove', \{ id \}\)/u)
  assert.match(source, /if \(removeId !== id\) \{ setRemoveId\(id\); return \}/u)
  assert.match(source, /removeId === candidate\.id \? t\('removeConfirm'\)/u)
  assert.doesNotMatch(source, /accountId|\.access\b|\.refresh\b/u)
})

test('account settings identify accounts by sanitized clickable email with privacy masking by default', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /candidate\.email/u)
  assert.match(source, /maskEmail/u)
  assert.match(source, /emailVisible/u)
  assert.match(source, /aria-pressed=\{emailVisible\}/u)
  assert.match(source, /setEmailVisible/u)
  assert.match(source, /emailVisible \? candidate\.email/u)
  assert.doesNotMatch(source, /accountId|accessToken|refreshToken/u)
})

test('email privacy mode resets when the signed-in account or account set changes', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /emailVisibilityKey/u)
  assert.match(source, /setEmailVisible\(false\)/u)
  assert.match(source, /emailVisible && emailVisibilityKey === accountVisibilityKey/u)
})

test('account status stays concise and leaves email identification to the account list', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /accountReady \? signedIn \? t\('connected'\) : t\('disconnected'\) : t\('accountLoading'\)/u)
  const status = source.match(/<div className="codexSubscriptionStatus"[\s\S]*?<\/div>/u)?.[0] ?? ''
  assert.doesNotMatch(status, /AccountEmail/u)
})

test('adding an account offers only login methods and assigns an internal fallback label', async () => {
  const source = await text('src/client.jsx')
  assert.doesNotMatch(source, /accountLabel|setAccountLabel|t\('accountLabel'\)/u)
  assert.match(source, /adding && label === undefined \? `Account \$\{accounts\.length \+ 1\}` : label/u)
  assert.match(source, /onClick=\{\(\) => begin\('browser'\)\}>\{t\('browserLogin'\)\}/u)
  assert.match(source, /onClick=\{\(\) => begin\('device_code'\)\}>\{t\('deviceLogin'\)\}/u)
})

test('quota resets render one compact action per returned credit without exposing its provider id', async () => {
  const [client, host, usage] = await Promise.all([
    text('src/client.jsx'), text('src/reset-credits.js'), text('src/usage.js'),
  ])
  assert.match(client, /resetCredits\.credits/u)
  assert.match(client, /credit\.ref/u)
  assert.match(client, /credit\.name/u)
  assert.match(client, /credit\.expiresAt/u)
  assert.match(client, /reset-credit\/prepare['"],\s*\{\s*creditRef/u)
  assert.match(host, /creditRef/u)
  assert.match(host, /creditId/u)
  assert.match(host, /creditRef[\s\S]*creditId|creditId[\s\S]*creditRef/u)
  assert.match(usage, /credits:\s*available/u)
  assert.doesNotMatch(client, /resetCreditsValue|codexSubscriptionResetSummary/u)
  assert.doesNotMatch(client, /credit\.id|creditId/u)
})

test('quota reset inspection refreshes when the account or usage snapshot changes', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /usageRefreshGeneration/u)
  assert.match(source, /refreshKey=\{`\$\{resetKey\}:\$\{usageRefreshGeneration\}`\}/u)
  assert.match(source, /\}, \[rpc, count, refreshKey\]\)/u)
  assert.match(source, /setCredits\(\[\]\)/u)
})

test('preference writes keep ready surfaces mounted while persistence is pending', async () => {
  const [client, controller] = await Promise.all([text('src/client.jsx'), text('src/preference-controller.js')])
  assert.match(controller, /status: current\.status/u)
  assert.doesNotMatch(controller, /status: updating \? ['"]updating['"] : current\.status/u)
  assert.match(controller, /pendingPatch/u)
  assert.match(controller, /const value = pendingPatch === undefined \? current\.value/u)
  assert.match(controller, /saving: updating/u)
  assert.match(controller, /if \(!updating\) failedPatch = undefined/u)
  assert.match(client, /quotaEnabled = preferenceSnapshot\.status === ['"]ready['"]/u)
  assert.match(client, /codexSubscriptionQuotaModes[^\n]*data-saving=\{snapshot\.saving/u)
  assert.match(client, /codexSubscriptionSearchChoices[^\n]*data-saving=\{snapshot\.saving/u)
  assert.match(client, /\.codexSubscriptionQuotaModes\[data-saving=true\].*opacity:1/u)
  assert.match(client, /\.codexSubscriptionSearchChoices\[data-saving=true\].*opacity:1/u)
})

test('support diagnostics stay compact without an extra expand step', async () => {
  const source = await text('src/client.jsx')
  assert.doesNotMatch(source, /diagnosticsOpen|diagnosticsClose|setDiagnosticsOpen|aria-expanded=\{diagnosticsOpen\}/u)
  assert.match(source, /codexSubscriptionDiagnostics[\s\S]*t\('diagnosticsLoad'\)/u)
  assert.match(source, /report === undefined \? null : <pre>/u)
  assert.match(source, /diagnosticsCopy/u)
})

test('generated image preview uses a native full-screen canvas and explicit edit handoff', async () => {
  const [source, viewer, styles] = await Promise.all([
    text('src/client.jsx'), text('src/subscription-image-viewer.jsx'), text('src/subscription-image-viewer-styles.js'),
  ])
  assert.match(source, /imageDownload/u)
  assert.match(viewer, /download=\{downloadName\(item\.name\)\}/u)
  assert.match(source, /imageBeta/u)
  assert.match(viewer, /IconDownloadOutline16/u)
  assert.match(viewer, /imageAnnotation/u)
  assert.match(source, /attachForEdit/u)
  assert.match(source, /attachImageFiles/u)
  assert.match(await text('src/image-composer.js'), /input\.addImages/u)
  assert.match(source, /input\.setDraft/u)
  assert.match(source, /imageEditDefault/u)
  assert.match(source, /imageRegionNotes/u)
  assert.match(viewer, /event\.key === 'Enter' && !event\.shiftKey/u)
  assert.match(viewer, /event\.stopPropagation\(\)\s+event\.nativeEvent/u)
  assert.doesNotMatch(source, /imageReferenceRole|IMAGE_REFERENCE_ROLES|referenceRole === role\.id/u)
  assert.match(source, /buildImageEditDraft/u)
  assert.match(viewer, /event\.key === ['"]Tab['"]/u)
  assert.match(viewer, /querySelectorAll\(/u)
  assert.match(styles, /border-radius:999px/u)
  assert.match(styles, /object-fit:contain/u)
  assert.doesNotMatch(source, /continue refining this image|继续在当前会话描述修改内容/u)
  assert.doesNotMatch(source, /codexGeneratedImageLightbox|codexGeneratedImageTopbar|codexGeneratedImageComments/u)
})

test('support diagnostics includes a direct repository feedback action', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /SUPPORT_ISSUE_URL/u)
  assert.match(source, /feedbackOpen/u)
  assert.match(source, /target="_blank"/u)
})

test('settings keep support diagnostics actionable and omit internal cache or route policy copy', async () => {
  const source = await text('src/client.jsx')
  assert.doesNotMatch(source, /CacheDiagnostics|Technical diagnostics|技术诊断|codexSubscriptionSafety/u)
  assert.match(source, /diagnosticsLoad/u)
  assert.doesNotMatch(source, /routePolicy|noFallback|searchIntro|quickQuotaHint|usageIntro|codexSubscriptionIntro|codexSubscriptionRoutePolicy/u)
})

test('account and preference failures stop loading and offer an in-place retry', async () => {
  const source = await text('src/client.jsx')
  assert.match(source, /accountSnapshot\.status === 'error'\s*\?\s*<AccountFailureCard/u)
  assert.match(source, /<AccountFailureCard/u)
  assert.match(source, /accountRetry/u)
  assert.match(source, /accountRetrying/u)
  assert.match(source, /accountStatus\.retry\(\)/u)
  assert.match(source, /void accountStatus\.load\(\)/u)
  assert.match(source, /void preference\.refreshModels\(\)/u)
  assert.match(source, /accountStatus\.reload\(\)/u)
  assert.match(source, /accountStatus\.dispose\(\)/u)
  assert.match(source, /preference\.retry\(\)/u)
  assert.match(source, /preferenceRetry/u)
  assert.match(source, /role=['"]alert['"][\s\S]*?Button/u)
  assert.match(source, /account === undefined \? null : <UsageCard/u)
  assert.doesNotMatch(source, /accountState === ['"](?:loading|error)['"]/u)
})

test('build emits host entries and a DSH module-loader client', async () => {
  const config = await text('tsdown.config.mjs')
  assert.match(config, /src\/index\.js/)
  assert.doesNotMatch(config, /src\/boundary\.js/)
  assert.match(config, /src\/client\.jsx/)
  assert.match(config, /window\.__ModuleLoader__\.load/)
  assert.match(config, /['"]dsh-codex-subscription['"]/)
  assert.doesNotMatch(config, /wsl043/iu)
})

test('generated Codex images use a DSH-tokenized native viewer across supported releases', async () => {
  const [source, viewer, manifest, config] = await Promise.all([
    text('src/client.jsx'), text('src/subscription-image-viewer.jsx'), text('package.json'), text('tsdown.config.mjs'),
  ])
  assert.doesNotMatch(source, /from ['"]@deepseek-ai\/dsh-client-ui-attachment['"]/u)
  assert.match(source, /function CodexGeneratedImage/u)
  assert.match(source, /image\/original\/chunk/u)
  assert.match(source, /decodeImagePresentation\(block\?\.meta\)/u)
  assert.match(source, /crypto\.subtle\.digest\('SHA-256'/u)
  assert.match(source, /return ctx\.get\('nativeImageViewer'\)/u)
  assert.match(source, /catch \{\s*return undefined\s*\}/u)
  assert.match(source, /viewer\?\.open\?\.\(/u)
  assert.match(source, /download: original === undefined \? undefined/u)
  assert.match(source, /onInvoke: downloadOriginal/u)
  assert.doesNotMatch(source, /id: 'download-original'|imageDownloadOriginal|OriginalImageDownload/u)
  assert.match(source, /id: 'continue-editing'/u)
  assert.match(source, /onInvoke:\s*\(\{ annotations = \[\] \}\)/u)
  assert.match(source, /closeOnSuccess: true/u)
  assert.doesNotMatch(source, /codexGeneratedImageEditDock|request\.editor|imageEditPrompt\}\s*onChange/u)
  const viewerOpen = source.indexOf('getInternalImageViewer?.()?.open?.(request)')
  const fallbackOpen = source.indexOf('viewer?.open?.(request)', viewerOpen)
  assert.ok(viewerOpen >= 0 && fallbackOpen > viewerOpen, 'subscription image cards must keep annotation and edit actions even when the host has a generic native viewer')
  assert.match(source.slice(viewerOpen, fallbackOpen), /\(request\) === true\) return/u)
  assert.match(viewer, /event\.key === ['"]Escape['"]/u)
  assert.match(viewer, /role=['"]dialog['"]/u)
  assert.match(viewer, /aria-modal=['"]true['"]/u)
  assert.match(source, /tool\.call\.toolview/u)
  assert.match(source, /key:\s*['"]codex_image_generate['"]/u)
  assert.match(source, /imageUrl\(sessionId,\s*attachment\)/u)
  assert.match(source, /block\.content/u)
  assert.match(manifest, /@deepseek-ai\/dsh-client-ui-tool/u)
  assert.doesNotMatch(config, /@deepseek-ai\/dsh-client-ui-attachment/u)
})
