import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = path => readFile(new URL(`../${path}`, import.meta.url), 'utf8')

test('subscription client preserves editing actions in its own local overlay', async () => {
  const source = (await Promise.all(['src/client.jsx', 'src/client-images.jsx'].map(read))).join('\n')
  const viewer = await read('src/subscription-image-viewer.jsx')
  const transform = await read('src/subscription-image-transform.js')
  const styles = await read('src/subscription-image-viewer-styles.js')

  assert.match(source, /SubscriptionImageViewerService/u)
  assert.match(source, /slots\.inject\(['"]shell\.overlay['"]/u)
  assert.match(source, /getImageViewer\?\.\(\)/u)
  assert.match(source, /getInternalImageViewer\?\.\(\)\?\.open\?\.\(request\) === true[\s\S]*?viewer\?\.open\?\.\(request\)/u)
  assert.doesNotMatch(source, /installOfficialImageBridge|nativeImageButton|reflect\.provide\(['"]nativeImageViewer/u)
  assert.doesNotMatch(source, /codexGeneratedImageLightbox|codexGeneratedImageTopbar|codexGeneratedImageComments/u)
  assert.match(viewer, /useImageTransform\(`\$\{request\?\.revision\}:\$\{item\?\.id\}:\$\{item\?\.src\}`\)/u)
  assert.match(transform, /addEventListener\('wheel', wheel, \{ passive: false \}\)/u)
  assert.match(transform, /onPointerMove/u)
  assert.match(transform, /closest\('button,a,input,textarea,select'\)/u)
  assert.match(transform, /event\.currentTarget\.setPointerCapture\(event\.pointerId\)/u)
  assert.match(viewer, /\.\.\.\(!annotating \? pointerHandlers : \{\}\)/u)
  assert.match(viewer, /onClick=\{\(\) => \{ resetGesture\(\); setAnnotating/u)
  assert.match(viewer, /onLoad=\{\(\) => \{ measure\(\) \}\}/u)
  assert.match(viewer, /Math\.round\(transform\.zoom \* pixelScale \* 100\)/u)
  assert.match(viewer, /style=\{annotationPosition\(annotation\)\}/u)
  assert.match(viewer, /visibility: geometry\.width > 0 \? 'visible' : 'hidden'/u)
  assert.doesNotMatch(viewer, /scale\(\$\{1 \/ transform\.zoom\}\)/u)
  assert.match(viewer, /revision=\{request\.revision\}/u)
  assert.match(viewer, /key=\{`\$\{request\.revision\}:\$\{index\}:\$\{action\.id\}`\}/u)
  assert.match(viewer, /service\.getSnapshot\(\)\?\.revision !== revision/u)
  assert.match(viewer, /className="dcsiv-topbar"/u)
  assert.match(viewer, /className="dcsiv-inline-note"/u)
  assert.match(viewer, /event\.key === 'Enter' && !event\.shiftKey/u)
  assert.match(viewer, /stopImmediatePropagation/u)
  assert.match(viewer, /service\.setAnnotations\(item\.id, next\)/u)
  assert.match(viewer, /navigator\.clipboard\.writeText/u)
  assert.match(viewer, /item\.download === undefined/u)
  assert.match(viewer, /action\.onInvoke\(\{ annotations, item, src: item\.src \}\)/u)
  assert.match(styles, /\.dcsiv-topbar\{position:absolute;right:50%;bottom:22px/u)
  assert.match(styles, /\.dcsiv-inline-note\{position:absolute;bottom:34px/u)
  assert.doesNotMatch(styles, /\.niv-|\.codexGeneratedImage/u)
})
