import {
  QUICK_QUOTA_MODE_FIELD, QUICK_QUOTA_MODE_OFF, QUICK_QUOTA_MODE_PERCENT, QUICK_QUOTA_MODE_BAR, QUICK_QUOTA_MODE_FORECAST,
  SEARCH_PROVIDER_FIELD, SEARCH_PROVIDER_AUTO, SEARCH_PROVIDER_DSH, SEARCH_PROVIDER_CODEX, DEFAULT_SEARCH_PROVIDER,
  SPEED_MODE_FIELD, SPEED_MODE_STANDARD, SPEED_MODE_FAST, DEFAULT_SPEED_MODE,
  OUTPUT_VERBOSITY_FIELD, OUTPUT_VERBOSITY_DEFAULT, OUTPUT_VERBOSITY_LOW, OUTPUT_VERBOSITY_MEDIUM, OUTPUT_VERBOSITY_HIGH, DEFAULT_OUTPUT_VERBOSITY,
  CONTEXT_MODE_FIELD, CONTEXT_MODE_STANDARD, CONTEXT_MODE_EXTENDED, CONTEXT_MODE_CUSTOM, DEFAULT_CONTEXT_MODE,
} from './settings-contract.js'

// One enum contract feeds persisted Host schemas and RPC writes.
export const PREFERENCE_FIELDS = Object.freeze({
  connectionMode: { choices: ['sse', 'websocket'], default: 'sse', error: 'Invalid connection mode' },
  subagentBackend: { choices: ['dsh', 'codex'], default: 'dsh', error: 'Invalid subagent backend' },
  [QUICK_QUOTA_MODE_FIELD]: { choices: [QUICK_QUOTA_MODE_OFF, QUICK_QUOTA_MODE_PERCENT, QUICK_QUOTA_MODE_BAR, QUICK_QUOTA_MODE_FORECAST], error: 'Invalid quick quota preference' },
  [SEARCH_PROVIDER_FIELD]: { choices: [SEARCH_PROVIDER_AUTO, SEARCH_PROVIDER_DSH, SEARCH_PROVIDER_CODEX], default: DEFAULT_SEARCH_PROVIDER, error: 'Invalid search provider preference' },
  [SPEED_MODE_FIELD]: { choices: [SPEED_MODE_STANDARD, SPEED_MODE_FAST], default: DEFAULT_SPEED_MODE, error: 'Invalid speed mode preference' },
  [OUTPUT_VERBOSITY_FIELD]: { choices: [OUTPUT_VERBOSITY_DEFAULT, OUTPUT_VERBOSITY_LOW, OUTPUT_VERBOSITY_MEDIUM, OUTPUT_VERBOSITY_HIGH], default: DEFAULT_OUTPUT_VERBOSITY, error: 'Invalid output verbosity preference' },
  [CONTEXT_MODE_FIELD]: { choices: [CONTEXT_MODE_STANDARD, CONTEXT_MODE_EXTENDED, CONTEXT_MODE_CUSTOM], default: DEFAULT_CONTEXT_MODE, error: 'Invalid context mode preference' },
})
